name: Node.js CD 

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Deploy using ssh 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }} 
        port: 22 
        script: |
          cd ~/tgbot_reminder # Переход в директорию с проектом на сервере
          git pull origin main # Вытягивание последних изменений из ветки main
          git status # Проверка состояния git-репозитория
          npm install --only=prod # Установка только продакшн-зависимостей
          pm2 restart tg-bot # Перезапуск процесса tg-bot с помощью PM2
